In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_hdf('./data/car.h5')

In [15]:
df.head()

,breadcrumb,created_at,price_currency,price_details,price_value,seller_address,seller_name,seller_type,feature_czujniki-parkowania-przednie,feature_poduszka-powietrzna-chroniąca-kolana,...,param_pearl,param_stan,param_wersja,param_emisja-co2,param_body-type,param_matowy,param_bezwypadkowy,param_akryl-(niemetalizowany),param_monthly-payment-value,car_id
0,"[Osobowe, Dacia, Logan, Dacia Logan II (2012-)]","13:23, 5 marca 2018",PLN,Cena Brutto,45100.0,"Krasne 7A - 36-007 Krasne, rzeszowski, Podkarp...",AUTO SPEKTRUM,Dealer,False,False,...,None,Nowe,II (2012-),None,None,None,Tak,None,None,0
2,"[Osobowe, Peugeot, 3008, Peugeot 3008 I (2009-...","15:48, 5 marca 2018",PLN,"Cena Brutto, Do negocjacji, Faktura VAT",28000.0,"Tomaszów Mazowiecki, tomaszowski, Łódzkie",None,Osoba prywatna,False,False,...,None,Używane,I (2009-2016),None,None,None,Tak,None,None,2
3,"[Osobowe, Porsche, Cayenne, Porsche Cayenne II...","06:30, 4 marca 2018",PLN,"Cena Netto, Do negocjacji, Faktura VAT",229500.0,"Kępińska 24a - 63-640 Bralin, kępiński, Wielko...",P.W. GRIB,Dealer,True,True,...,None,Używane,II (2010-),None,None,None,None,None,None,3
4,"[Osobowe, Peugeot, 308, Peugeot 308 T7 (2008-2...","08:46, 3 marca 2018",PLN,"Cena Brutto, Do negocjacji",19500.0,"Limanowa, limanowski, Małopolskie",None,Osoba prywatna,False,False,...,None,Używane,T7 (2008-2013),None,None,None,Tak,None,None,4
5,"[Osobowe, Volkswagen, Golf, Volkswagen Golf VI...","20:00, 3 marca 2018",PLN,"Cena Brutto, Faktura VAT",164900.0,"Niciarniana 51/53 - 92-320 Łódź, Śródmieście (...",KROTOSKI-CICHY Niciarniana 51/53 oraz Dąbrowsk...,Dealer,True,True,...,None,Używane,VII (2012-),None,None,None,Tak,None,None,5

In [17]:
df.shape

(106494, 155)

In [18]:
df.sample(5)

,breadcrumb,created_at,price_currency,price_details,price_value,seller_address,seller_name,seller_type,feature_czujniki-parkowania-przednie,feature_poduszka-powietrzna-chroniąca-kolana,...,param_pearl,param_stan,param_wersja,param_emisja-co2,param_body-type,param_matowy,param_bezwypadkowy,param_akryl-(niemetalizowany),param_monthly-payment-value,car_id
97353,"[Osobowe, Audi, A6, Audi A6 C5 (1997-2004)]","17:07, 4 marca 2018",PLN,"Cena Brutto, Do negocjacji",10900.0,"Bodzentyn, kielecki, Świętokrzyskie",None,Osoba prywatna,False,True,...,None,Używane,C5 (1997-2004),None,None,None,Tak,None,None,97353
73009,"[Osobowe, Renault, Clio, Renault Clio II (1998...","10:32, 1 marca 2018",PLN,"Cena Brutto, Do negocjacji",8700.0,"Krakowska 14 - 32-090 Słomniki, krakowski, Mał...","F.H.U.""OLO""",Dealer,False,False,...,None,Używane,II (1998-2012),None,None,None,Tak,None,None,73009
15845,"[Osobowe, Ford, Fiesta, Ford Fiesta Mk7 (2008-)]","20:22, 25 lutego 2018",PLN,"Cena Brutto, Do negocjacji",19500.0,"Sopot, Pomorskie, Górny Sopot",None,Osoba prywatna,False,False,...,None,Używane,Mk7 (2008-),None,None,None,Tak,None,None,15845
127944,"[Osobowe, Peugeot, Boxer]","14:32, 3 marca 2018",PLN,Cena Brutto,8600.0,"Nowe Aleksandrowo, białostocki, Podlaskie",None,Osoba prywatna,False,False,...,None,Używane,None,None,None,None,None,None,None,127944
97262,"[Osobowe, Volkswagen, Golf, Volkswagen Golf VI...","20:55, 23 lutego 2018",PLN,"Cena Brutto, Do negocjacji",34900.0,"Zambrów, zambrowski, Podlaskie",None,Osoba prywatna,False,False,...,None,Używane,VI (2008-2013),None,None,None,None,None,None,97262